export const mapStrings = {
  ar: {
    eyebrow: 'الدليل الجغرافي التعليمي',
    title: 'المديريات والمدارس، في مكان واحد',
    intro:
      'استكشف المحافظات، وتصفّح دليل المديريات والمدارس من مصادره المتاحة.',
    schools: 'المدارس',
    directorates: 'المديريات والجهات',
    governorates: 'المحافظات',
    located: 'مواقع مدارس موثّقة',
    records: 'سجل مدرسي في الملف',
    search: 'ابحث بالعربية أو الإنجليزية',
    searchHint: 'اسم المدرسة أو المديرية أو الرقم الوطني…',
    filters: 'تصفية الدليل',
    governorate: 'المحافظة',
    directorate: 'المديرية / الجهة',
    type: 'التصنيف حسب المصدر',
    region: 'المنطقة',
    all: 'الكل',
    unknown: 'غير محدد في المصدر',
    unassigned: 'غير مرتبط بعد',
    wb: 'الضفة الغربية',
    gaza: 'قطاع غزة',
    reset: 'إعادة العرض',
    zoomIn: 'تكبير',
    zoomOut: 'تصغير',
    outline: 'الحدود',
    counts: 'عدد سجلات المدارس',
    loading: 'جارٍ تحميل البيانات…',
    error:
      'تعذّر تحميل بيانات الدليل. تأكد من تسجيل الدخول وتشغيل خدمة المنصة واستيراد البيانات، ثم حاول مجددًا.',
    retry: 'إعادة المحاولة',
    empty: 'لا توجد نتائج مطابقة.',
    prev: 'السابق',
    next: 'التالي',
    results: 'نتيجة',
    page: 'الصفحة',
    noLocation:
      'لا تتوفر إحداثيات لهذه المدرسة في المصدر. موقعها الدقيق غير معروض على الخريطة.',
    noDirectorate: 'لم يتوفر ربط موثّق لهذه المدرسة بمديرية تعليمية بعد.',
    unmappedRecords: 'سجلات غير مرتبطة بمحافظة',
    noBoundaryUnassigned:
      'لا تتوفر حدود جغرافية موثّقة لهذه الجهة في البيانات المرفقة.',
    noLinks:
      'الربط بين هذه المديرية والمدارس غير متوفر في البيانات المستوردة. هذا لا يعني عدم وجود مدارس تابعة لها.',
    noBoundary: 'حدود هذه المديرية غير مرفقة؛ التحديد الظاهر يخص المحافظة فقط.',
    showGovernorate: 'استعرض مدارس المحافظة',
    close: 'إغلاق التفاصيل',
    details: 'تفاصيل المدرسة',
    nationalCode: 'الرقم الوطني في المصدر',
    linked: 'سجلات المدارس المرتبطة',
    official: 'المصدر الرسمي',
    ministry: 'وزارة التربية والتعليم العالي',
    locationNote:
      'الملف المرفق لا يحتوي مواقع المدارس. جميع سجلاته متاحة في الدليل؛ ستظهر العلامات بعد إضافة إحداثيات موثّقة.',
    sourceNote:
      'الحدود: محافظات، وليست حدود مديريات تعليمية. تاريخ الحدود 2023-10-19؛ تاريخ بيانات المدارس غير مرفق.',
    directoryNote:
      'قائمة المديريات تجمع الأسماء المنشورة في دليلي الوزارة وeSchool؛ ليست إحصاءً وطنيًا مكتملًا أو آنيًا.',
    mapLabel:
      'خريطة تفاعلية لفلسطين التاريخية مع محافظات الضفة الغربية وقطاع غزة. استخدم الدليل لاختيار المناطق والمدارس بلوحة المفاتيح.',
    mapFailure:
      'تعذّر تشغيل الخريطة التفاعلية. جرّب متصفحًا يدعم WebGL؛ دليل المدارس والمديريات يبقى متاحًا.',
    mapLoading: 'جارٍ تجهيز الخريطة…',
    boundaryLabel: 'حدود المحافظات',
    historicalContext: 'فلسطين التاريخية · طبقة مرجعية',
    historicalContextNote: 'الشكل المرجعي لفلسطين التاريخية؛ بيانات الدليل الحالية تغطي الضفة الغربية وقطاع غزة.',
    contextSource: 'المصدر: جيومولغ',
    legend: 'جميع سجلات الملف حسب المحافظة',
    low: 'أقل',
    high: 'أكثر',
    hint: 'اختر محافظة على الخريطة لاستعراض مدارسها',
    schoolHint: 'قرّب الخريطة لإظهار المواقع الموثّقة',
    pointError: 'تعذّر تحميل مواقع المدارس لهذا النطاق.',
    truncated: 'بعض المواقع خارج حد العرض. قرّب الخريطة لنطاق أصغر.',
    loaded: 'بيانات مستوردة',
    cluster: 'مواقع مدارس مجمّعة',
    location: 'الموقع',
    locatedOnly: 'بإحداثيات',
    missingOnly: 'بدون إحداثيات',
    observatory: 'الخريطة البحثية',
    researchPending:
      'مؤشرات المشكلات والتميّز والفجوات تنتظر مصدر بيانات الأبحاث. الحدود الجغرافية متاحة، ولا تُعرض مؤشرات أو أرقام تجريبية.',
    directoryLink: 'افتح دليل المديريات والمدارس',
    noData: 'لم تُستورد البيانات بعد.',
    clear: 'مسح التصفية',
  },
  en: {
    eyebrow: 'Education geography',
    title: 'Directorates and schools, connected',
    intro:
      'Explore governorates and browse the available directorate and school directory.',
    schools: 'Schools',
    directorates: 'Directorates & agencies',
    governorates: 'Governorates',
    located: 'Verified school locations',
    records: 'School records in the file',
    search: 'Search in Arabic or English',
    searchHint: 'School, directorate, or national code…',
    filters: 'Filter the directory',
    governorate: 'Governorate',
    directorate: 'Directorate / agency',
    type: 'Source classification',
    region: 'Region',
    all: 'All',
    unknown: 'Not specified in source',
    unassigned: 'Not linked yet',
    wb: 'West Bank',
    gaza: 'Gaza Strip',
    reset: 'Reset view',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    outline: 'Boundaries',
    counts: 'School record count',
    loading: 'Loading data…',
    error:
      'The directory could not be loaded. Check that you are signed in, the platform API is running and the data is imported, then retry.',
    retry: 'Try again',
    empty: 'No matching results.',
    prev: 'Previous',
    next: 'Next',
    results: 'results',
    page: 'Page',
    noLocation:
      'This source has no coordinates for this school. Its precise location is not plotted.',
    noDirectorate:
      'A verified link between this school and an educational directorate is not available yet.',
    unmappedRecords: 'Records without a governorate',
    noBoundaryUnassigned:
      'Verified geographic boundaries for this agency were not supplied.',
    noLinks:
      'The imported data does not link schools to this directorate yet. This does not mean it has no schools.',
    noBoundary:
      'This directorate has no supplied boundary; the highlighted area is its governorate only.',
    showGovernorate: 'Browse schools in this governorate',
    close: 'Close details',
    details: 'School details',
    nationalCode: 'National code in source',
    linked: 'Linked school records',
    official: 'Official source',
    ministry: 'Ministry of Education and Higher Education',
    locationNote:
      'The uploaded file has no school coordinates. All its records are available in the directory; markers appear after verified coordinates are added.',
    sourceNote:
      'Boundaries represent governorates, not educational directorates. Boundary date: 2023-10-19. School data date was not supplied.',
    directoryNote:
      'Directorate names combine the published ministry and eSchool directories; this is not a complete or live national census.',
    mapLabel:
      'Interactive historical Palestine map with West Bank and Gaza Strip governorates. Use the directory to select areas and schools with the keyboard.',
    mapFailure:
      'The interactive map could not start. Try a WebGL-compatible browser; the school and directorate directory remains available.',
    mapLoading: 'Preparing the map…',
    boundaryLabel: 'Governorate boundaries',
    historicalContext: 'Historical Palestine · Reference layer',
    historicalContextNote: 'Historical Palestine reference outline; current directory data covers the West Bank and Gaza Strip.',
    contextSource: 'Source: Geomolg',
    legend: 'All file records by governorate',
    low: 'Fewer',
    high: 'More',
    hint: 'Select a governorate to browse its schools',
    schoolHint: 'Zoom in to show verified school locations',
    pointError: 'School locations could not be loaded for this view.',
    truncated:
      'Some locations exceed the display limit. Zoom into a smaller area.',
    loaded: 'Imported records',
    cluster: 'Clustered school locations',
    location: 'Location',
    locatedOnly: 'With coordinates',
    missingOnly: 'Without coordinates',
    observatory: 'Research map',
    researchPending:
      'Problem, excellence, and gap indicators await a research data source. Geographic boundaries are available; no demo indicators or figures are displayed.',
    directoryLink: 'Open the school and directorate directory',
    noData: 'Data has not been imported yet.',
    clear: 'Clear filters',
  },
}

export function schoolTypeLabel(value, language) {
  const labels = {
    government: ['حكومية', 'Government'],
    private: ['خاصة', 'Private'],
    unrwa: ['وكالة الغوث', 'UNRWA'],
    pa: ['PA — كما ورد في المصدر', 'PA — source classification'],
    na: ['غير محدد', 'Not specified'],
  }
  return labels[value]?.[language === 'ar' ? 0 : 1] || value
}
