

export const platformPagesEn = {
  '/about': {
    eyebrow: 'About PARP',
    title: 'Knowledge starts in the field',
    description: 'PARP is an integrated national digital platform that supports the full action-research cycle: identifying a problem, training, preparing a proposal, review, implementation, publication, analysis, and turning findings into usable recommendations.',
    primary: 'Vision and mission',
    sections: [
      {
        title: 'Vision',
        body: 'To make PARP the leading Palestinian national reference for action research in education and a leading Arab platform for producing, managing, and applying practice-based educational knowledge.',
      },
      {
        title: 'Mission',
        body: 'To empower education practitioners and researchers to produce high-quality action research through one environment for training, mentoring, review, publication, and analysis.',
      },
      {
        title: 'Platform values',
        items: ['Scientific rigor and research integrity', 'Transparency and fairness in review', 'Inclusion and accessibility', 'Privacy and data protection', 'National partnership and mutual learning', 'Innovation and continuous improvement'],
      },
      {
        title: 'Strategic goals',
        items: ['A unified national repository for action research', 'A shared methodology through the guide and template', 'Digital conference and review management', 'Continuous training and mentoring for researchers', 'Turning data into indicators, reports, and recommendations'],
      },
    ],
  },
  '/conference': {
    kind: 'conference',
    eyebrow: 'National Conference',
    title: 'The conference cycle in one digital pathway',
    description: 'A space for managing the national conference journey from announcement and registration to review, results, certificates, and archiving.',
    primary: 'Take part in the conference',
    sections: [
      { title: 'Before the conference', items: ['Announcement', 'Registration', 'Workshops', 'Proposal submission'] },
      { title: 'Scientific track', items: ['Research submission', 'Peer review', 'Feedback and decisions', 'Revised-version review'] },
      { title: 'During the conference', items: ['Program', 'Sessions and workshops', 'Results'] },
      { title: 'After the conference', items: ['Certificates', 'Archive', 'Linking research to the national repository'] },
    ],
  },
  '/repository': {
    kind: 'repository',
    eyebrow: 'National Repository',
    title: 'A national memory for action research',
    description: 'A unified repository that preserves accepted research and makes it available for search, download, and citation under an approved publication policy.',
    primary: 'Explore research',
    sections: [
      { title: 'Search and discovery', items: ['All research', 'Advanced search', 'Categories', 'Related research'] },
      { title: 'Research page', items: ['Title and abstract', 'Researchers and institution', 'Field and keywords', 'Intervention and findings'] },
      { title: 'Scholarly access', items: ['Full file', 'Download', 'Citation format', 'Usage statistics'] },
      { title: 'Standardized data', items: ['School, directorate, and governorate', 'Stage and specialization', 'Problem and question', 'Intervention type and data tools'] },
    ],
  },
  '/guide': {
    kind: 'guide',
    eyebrow: 'Palestinian Guide',
    title: 'A unified reference for action research',
    description: 'An interactive guide and downloadable edition that help researchers understand action research and build studies through a shared methodology and examples from the Palestinian context.',
    primary: 'Browse the guide',
    sections: [
      { title: 'Research foundations', items: ['Nature of action research', 'Ethics', 'Choosing the problem', 'Formulating the question and objectives'] },
      { title: 'Design and implementation', items: ['Intervention design', 'Data collection tools', 'Results analysis', 'Reflection and recommendations'] },
      { title: 'Supporting materials', items: ['Palestinian examples', 'Videos', 'Frequently asked questions', 'Updates'] },
      { title: 'Access formats', items: ['Interactive version', 'PDF', 'Applied examples'] },
    ],
  },
  '/template': {
    kind: 'template',
    eyebrow: 'Palestinian Template',
    title: 'Build your research step by step',
    description: 'A unified template that helps researchers complete the elements of a study in a format that supports review and publication without replacing scientific judgment.',
    primary: 'Start the template',
    sections: [
      { title: 'Starting information', items: ['Researcher and institution data', 'Title and keywords', 'Problem and context', 'Question and objectives'] },
      { title: 'Research plan', items: ['Target group', 'Intervention and action plan', 'Data collection tools'] },
      { title: 'Outputs', items: ['Results and analysis', 'Professional reflection', 'Recommendations', 'References and appendices'] },
      { title: 'Template tools', items: ['Interactive template', 'Step-by-step builder', 'Examples', 'Completion check', 'Word version'] },
    ],
  },
  '/training': {
    eyebrow: 'Training Center',
    title: 'Continuous learning for every researcher',
    description: 'Self-paced pathways, live training, assessment, and certificates, with progress records linked to each user role and specialization.',
    primary: 'Explore training',
    sections: [
      { title: 'Courses', items: ['Self-paced learning', 'Role-based pathways', 'Assessments', 'Progress record'] },
      { title: 'Live training', items: ['Workshops', 'Live sessions', 'Mentoring', 'Topic groups'] },
      { title: 'Assessment', items: ['Pre- and post-assessments', 'Completion tracking', 'Measuring improvement'] },
      { title: 'Certificates', items: ['Digital certificates', 'Achievement record', 'Linking certificates to the research profile'] },
    ],
  },
  '/library': {
    eyebrow: 'Digital Library',
    title: 'Trusted resources for researchers and practitioners',
    description: 'A library bringing together books, guides, articles, presentations, recordings, and trusted links related to action research.',
    primary: 'Browse the library',
    sections: [
      { title: 'Written resources', items: ['Books', 'Guides', 'Articles', 'Presentations'] },
      { title: 'Media', items: ['Recordings', 'Videos', 'Training materials'] },
      { title: 'Trusted links', body: 'Curated links connected directly to action-research topics and educational practice.' },
      { title: 'Connected knowledge', body: 'Resources are linked with the guide, training, and related research for easier access and reuse.' },
    ],
  },
  '/assistant': {
    eyebrow: 'AI Assistant',
    title: 'Structured methodological support',
    description: 'An assistant that supports researchers linguistically, methodologically, and procedurally within clear safeguards against plagiarism and uncritical reliance.',
    primary: 'Explore its capabilities',
    sections: [
      { title: 'Improve wording', items: ['Refine titles and questions', 'Suggest keywords', 'Review consistency'] },
      { title: 'Citation support', items: ['APA', 'Initial reference organization', 'Formatting review'] },
      { title: 'Initial analysis', body: 'Early-stage support that helps organize thinking without replacing scientific analysis or human judgment.' },
      { title: 'Ethical safeguards', items: ['Ethics alerts', 'Prevent uncritical reliance', 'Disclosure and human review'] },
    ],
  },
  '/observatory': {
    eyebrow: 'National Observatory',
    title: 'Read the trends emerging from the field',
    description: 'An interface for monitoring trends, gaps, and educational issues through maps, national reports, and governorate and directorate reports.',
    primary: 'Explore the observatory',
    sections: [
      { title: 'Map', items: ['Geographic distribution', 'Governorates', 'Directorates', 'Research fields'] },
      { title: 'Trends', items: ['Recurring issues', 'Research gaps', 'Priority topics'] },
      { title: 'Reports', items: ['National reports', 'Governorate reports', 'Directorate reports'] },
      { title: 'From evidence to decisions', body: 'Move from an indicator to the related research and evidence for deeper interpretation.' },
    ],
  },

    '/observatory/map': {
    kind: 'observatory-map',
    eyebrow: 'Geographic Map',
    title: 'Palestine Education 3D Map',
    description: 'An interactive geographic representation of directorates and schools, showing educational data by indicator: research, interactions, teachers, problems.',
    primary: 'Explore the map',
    sections: [],
  },

  '/dashboard': {
    eyebrow: 'Dashboard',
    title: 'Measure use, quality, and impact',
    description: 'An operational and strategic dashboard covering access, production, quality, efficiency, training, usage, impact, and sustainability indicators.',
    primary: 'View indicators',
    sections: [
      { title: 'Access and production', items: ['Active users', 'Schools and directorates', 'Proposals', 'Published research'] },
      { title: 'Quality and efficiency', items: ['Eligible research', 'Review scores', 'Revision rate', 'Process time'] },
      { title: 'Training and usage', items: ['Enrollment and completion', 'Improvement', 'Downloads and visits', 'Most-used resources'] },
      { title: 'Impact and sustainability', items: ['Implemented interventions', 'Sustained practice', 'Recommendations', 'Updates and partnerships'] },
    ],
  },
  '/community': {
    eyebrow: 'Research Community',
    title: 'A professional space for mutual learning',
    description: 'A moderated professional community for questions, experience exchange, thematic groups, and mentoring among practitioners and researchers.',
    primary: 'Enter the community',
    sections: [
      { title: 'Questions and discussions', body: 'An organized space for discussing action-research issues and educational practice.' },
      { title: 'Topic groups', items: ['Specialized fields', 'Shared issues', 'Practices and experiences'] },
      { title: 'Mentoring', body: 'Connect researchers with professional and academic expertise that supports progress through the research journey.' },
      { title: 'Experience exchange', body: 'Share lessons learned, interventions, and promising practices in a professional environment.' },
    ],
  },
  '/institutions': {
    eyebrow: 'Schools & Directorates',
    title: 'Institutional profiles that show progress and achievement',
    description: 'Profiles for schools and directorates showing researchers, studies, achievements, indicators, and trends over time.',
    primary: 'Explore institutions',
    sections: [
      { title: 'Institution profile', items: ['Profile data', 'Researchers', 'Research', 'Achievements'] },
      { title: 'Indicators', items: ['Participation', 'Quality', 'Trends', 'Time-based comparison'] },
      { title: 'Follow-up', items: ['Researcher progress', 'Needs', 'Reports'] },
      { title: 'Highlighting achievement', body: 'Connect institutional achievements with the research, researchers, and published outcomes available on the platform.' },
    ],
  },
  '/excellence': {
    eyebrow: 'Hall of Excellence',
    title: 'Highlight outstanding work through published criteria',
    description: 'A space connecting awards and recognition with research and researcher profiles through clear, documentable criteria.',
    primary: 'Browse the Hall of Excellence',
    sections: [
      { title: 'Excellence categories', items: ['Best research', 'Best researcher', 'Best school', 'Best directorate'] },
      { title: 'Supporting roles', items: ['Outstanding supervisor', 'Outstanding reviewer'] },
      { title: 'Awards archive', body: 'Preserve previous editions and make outstanding examples available for reference.' },
      { title: 'Scholarly connection', body: 'Each recognition links to the research, the researcher profile, and the published platform data.' },
    ],
  },
  '/news': {
    kind: 'news',
    eyebrow: 'News & Events',
    title: 'Everything happening on the platform in one place',
    description: 'Announcements, calendar items, success stories, workshops, conferences, and updates connected to the life of the platform and its research community.',
    primary: 'Latest updates',
    sections: [
      { title: 'Announcements', body: 'Platform announcements, dates, and opportunities related to the conference, training, and participation.' },
      { title: 'Events', items: ['Workshops', 'Conferences', 'Meetings', 'Calendar'] },
      { title: 'Success stories', body: 'Experiences and examples that reflect the impact of action research in the field.' },
      { title: 'Updates', body: 'Updates to platform content and newly introduced services.' },
    ],
  },
  '/support': {
    kind: 'support',
    eyebrow: 'Technical Support',
    title: 'Clear support at every step',
    description: 'A knowledge base, frequently asked questions, contact channels, and support tickets with request tracking.',
    primary: 'Get help',
    sections: [
      { title: 'Knowledge base', body: 'Practical guidance for using the platform and solutions to common questions.' },
      { title: 'Frequently asked questions', body: 'Short answers to common questions about accounts, research, and services.' },
      { title: 'Support tickets', items: ['Create a request', 'Track status', 'Follow the response'] },
      { title: 'Contact channels', body: 'Clear routes for contacting the platform team based on the type of support needed.' },
    ],
  },
  '/account': {
    eyebrow: 'Account & Profile',
    title: 'Your research journey starts with your digital profile',
    description: 'An interface for account access, digital identity, research profile, progress, certificates, and activity according to the user role and permissions.',
    primary: 'Access your account',
    sections: [
      { title: 'Identity', items: ['Create an account', 'Verify identity', 'Choose field and role'] },
      { title: 'Research journey', items: ['Training', 'Guide and template', 'Proposal', 'Review', 'Final research'] },
      { title: 'Research profile', items: ['Work', 'Certificates', 'Activity', 'Interests'] },
      { title: 'Role-based permissions', items: ['Researcher', 'Supervisor', 'Reviewer', 'School principal', 'Directorate coordinator', 'Trainer'] },
    ],
  },
}
