// Illustrative teaching templates, not published or validated research findings.
export const practices = [
  { id: 'exit-ticket', category: 'assessment', ar: { title: 'بطاقة الخروج', intro: 'سؤال قصير في نهاية الحصة يساعد على تحديد ما يحتاج إلى مراجعة.', steps: ['حدّد هدفًا واحدًا للحصة.', 'اطلب إجابة قصيرة من جميع الطلبة.', 'صنّف الإجابات واستخدمها لتخطيط الحصة التالية.'], tools: 'بطاقة ورقية أو نموذج رقمي وسجل ملاحظة.', impact: 'قارن فهم المفهوم قبل المراجعة وبعدها، ووثّق التعديلات دون افتراض نجاح التدخل.' }, en: { title: 'Exit tickets', intro: 'A short end-of-lesson question helps identify what needs revisiting.', steps: ['Choose one learning objective.', 'Collect a brief answer from each learner.', 'Group responses and use them to plan the next lesson.'], tools: 'Paper tickets or a digital form and an observation log.', impact: 'Compare understanding before and after revisiting the concept. Document changes without assuming the intervention succeeded.' } },
  { id: 'think-pair-share', category: 'participation', ar: { title: 'فكّر، زاوج، شارك', intro: 'تنظيم المشاركة بإتاحة وقت للتفكير الفردي ثم النقاش الثنائي.', steps: ['اعرض سؤالًا مفتوحًا وحدّد وقتًا للتفكير.', 'اطلب تبادل الأفكار في أزواج.', 'ناقش الإجابات مع الصف ودوّن ملاحظات المشاركة.'], tools: 'سؤال موجّه وبطاقة ملاحظة المشاركة.', impact: 'تتبّع تنوّع المشاركين وجودة التفسيرات عبر عدة حصص مع مراعاة اختلاف السياق.' }, en: { title: 'Think, pair, share', intro: 'Structure participation through individual thinking followed by paired discussion.', steps: ['Present an open question and allow thinking time.', 'Ask learners to exchange ideas in pairs.', 'Discuss responses as a class and record participation observations.'], tools: 'A guiding question and a participation observation sheet.', impact: 'Track participation and explanation quality across lessons while accounting for differences in context.' } },
  { id: 'worked-example', category: 'learning', ar: { title: 'المثال المحلول المتدرّج', intro: 'الانتقال من مثال مشروح إلى حل مستقل مع تقليل الدعم تدريجيًا.', steps: ['قدّم مثالًا مع تفسير خطواته.', 'اعرض مثالًا ناقص الخطوات ليكمله الطلبة.', 'قدّم مهمة مستقلة وسجّل مواضع الصعوبة.'], tools: 'أمثلة متدرجة ومهمة قبلية وبعدية متكافئة.', impact: 'قارن أنواع الأخطاء ومستوى الاستقلالية، ثم تأمّل النتائج وعدّل الدعم.' }, en: { title: 'Faded worked examples', intro: 'Move from a explained example to independent work by gradually reducing support.', steps: ['Present an example and explain its steps.', 'Offer a partially completed example.', 'Set an independent task and record difficulties.'], tools: 'Scaffolded examples and comparable pre- and post-tasks.', impact: 'Compare error patterns and independence, reflect on the findings and adjust support.' } },
]
export function filterPractices(items, query, category) {
  const normalize = (s) => s.normalize('NFKD').replace(/[\u064b-\u065f\u0670\u0640]/g, '').toLowerCase()
  const q = normalize(query.trim())
  return items.filter((item) => (category === 'all' || item.category === category) && normalize(JSON.stringify([item.ar, item.en])).includes(q))
}
